<?php

namespace AppBundle\Xml;

use AppBundle\Document\Feed;
use Doctrine\ODM\MongoDB\DocumentManager;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Routing\RouterInterface;

class Render
{
    protected $generator;
    protected $dm;
    protected $router;

    /**
     * @param string          $generator Like "Generated by foobar"
     * @param DocumentManager $dm
     * @param RouterInterface $router
     */
    public function __construct($generator, DocumentManager $dm, RouterInterface $router)
    {
        $this->generator = $generator;
        $this->dm = $dm;
        $this->router = $router;
    }

    /**
     * Render the feed in specified format.
     *
     * @param Feed $feed Feed to render
     *
     * @throws \InvalidArgumentException if given format formatter does not exists
     *
     * @return string
     */
    public function doRender(Feed $feed)
    {
        $items = $this->dm->getRepository('AppBundle:FeedItem')->findByFeed(
            $feed->getId(),
            $feed->getSortBy()
        );

        $feedUrl = $this->router->generate(
            'feed_xml',
            ['slug' => $feed->getSlug()],
            UrlGeneratorInterface::ABSOLUTE_URL
        );

        switch ($feed->getFormatter()) {
            case 'rss':
                $formatter = new Formatter\RssFormatter($feed, $items, $feedUrl, $this->generator);
                break;
            case 'atom':
                $formatter = new Formatter\AtomFormatter($feed, $items, $feedUrl, $this->generator);
                break;
            default:
                throw new \InvalidArgumentException(
                    sprintf("Format '%s' is not available. Please see documentation.", $feed->getFormatter())
                );
        }

        return $formatter->render();
    }
}
