services:
###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:11.8.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: f43me
      MARIADB_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_mysql_data:/var/lib/mysql:rw
    restart: always
###< doctrine/doctrine-bundle ###

  nginx-php:
    build:
      context: ./docker
      dockerfile: ./Dockerfile-php8.2
    ports:
      - "8100:8100"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./:/usr/share/nginx/html
    env_file:
      - .env
      - .env.local
    environment:
      DATABASE_URL: "mysql://root:root@database:3306/f43me?serverVersion=mariadb-11.8.6&charset=utf8mb4"
      LOCK_DSN: "flock"
    command: ["bash", "/usr/share/nginx/html/docker/launch-f43me.sh"]

volumes:
###> doctrine/doctrine-bundle ###
  database_mysql_data:
###< doctrine/doctrine-bundle ###
