version: "3.1"
services:
    # Mongo
    db:
        image: mvertes/alpine-mongo:3.4.10-0
        container_name: f43-me-db
        ports:
            - "27017:27017"

    # This container is responsible of building the frontend
    frontend-build:
        build: docker/frontend-build
        container_name: f43-me-frontend-build
        working_dir: /application
        volumes:
            - .:/application
        command:
            - "docker/frontend-build/start.sh"

    # This container is responsible of initialising the backend code - dies after it's finished doing its thing
    backend-build:
        build: docker/php-fpm
        depends_on:
            - db
        container_name: f43-me-backend-build
        working_dir: /application
        volumes:
            - .:/application
        command:
            - "docker/backend-build/build.sh"
        links:
            - db

    # PHP 7.2 setup - NOTE: no xdebug at this time available for 7.2
    webserver-72:
        image: nginx:alpine
        depends_on:
            - frontend-build
            - php-fpm-72
        container_name: f43-me-webserver-72
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8100:80"
        links:
            - php-fpm-72:php-fpm

    php-fpm-72:
        build: docker/php-fpm
        depends_on:
            - backend-build
        container_name: f43-me-php-fpm-72
        working_dir: /application
        environment:
            - SYMFONY_ENV=dev
        volumes:
            - .:/application
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
        links:
            - db
