FROM php:7.4-fpm

# Install nginx
RUN apt-get update \
    && apt-get install -y -q nginx libssl-dev build-essential vim git curl zlib1g-dev apt-utils libzip-dev librabbitmq-dev libtidy-dev unzip

RUN pecl install xdebug amqp tidy \
    && docker-php-ext-enable xdebug \
    && docker-php-ext-install zip \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-install bcmath \
    && docker-php-ext-install sockets \
    && docker-php-ext-install tidy \
    && docker-php-ext-enable amqp \
    && docker-php-ext-enable tidy

ADD ./fastcgi-php.conf /etc/nginx/snippets/fastcgi-php.conf
ADD ./upstream-php.conf /etc/nginx/conf.d/php7.4-fpm.conf
ADD ./vhost.sh /tmp/vhost.sh

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash

ENV NVM_DIR=/root/.nvm
ENV NODE_VERSION=v16

RUN . $HOME/.nvm/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default \
    && npm install -g yarn

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php \
    && php -r "unlink('composer-setup.php');" \
    && mv composer.phar /usr/sbin/composer

RUN apt-get clean \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
