<?php

namespace App\Xml;

use App\Entity\Feed;
use App\Repository\ItemRepository;
use App\Xml\Formatter\AtomFormatter;
use App\Xml\Formatter\RssFormatter;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Routing\RouterInterface;

class Render
{
    /**
     * @param string $generator Like "Generated by foobar"
     */
    public function __construct(protected string $generator, protected ItemRepository $itemRepository, protected RouterInterface $router)
    {
    }

    /**
     * Render the feed in specified format.
     *
     * @param Feed $feed Feed to render
     *
     * @throws \InvalidArgumentException if given format formatter does not exists
     */
    public function doRender(Feed $feed): string
    {
        $items = $this->itemRepository->findByFeed(
            $feed->getId(),
            $feed->getSortBy()
        );

        $feedUrl = $this->router->generate(
            'feed_xml',
            ['slug' => $feed->getSlug()],
            UrlGeneratorInterface::ABSOLUTE_URL
        );

        $formatter = match ($feed->getFormatter()) {
            'rss' => new RssFormatter($feed, $items, $feedUrl, $this->generator),
            'atom' => new AtomFormatter($feed, $items, $feedUrl, $this->generator),
            default => throw new \InvalidArgumentException(\sprintf("Format '%s' is not available. Please see documentation.", $feed->getFormatter())),
        };

        return $formatter->render();
    }
}
