<?php

namespace j0k3r\FeedBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * FeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedRepository extends DocumentRepository
{
    public function findAllOrderedByDate()
    {
        return $this->createQueryBuilder()
            ->sort('updated_at', 'DESC')
            ->getQuery()
            ->execute();
    }
}
