<?php

namespace j0k3r\FeedBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * FeedLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedLogRepository extends DocumentRepository
{
    /**
     * Find all logs ordered by id desc
     *
     * @param  integer   $limit Items to retrieve
     *
     * @return Doctrine\ODM\MongoDB\EagerCursor
     */
    public function findAllOrderedById($limit = null)
    {
        $q = $this->createQueryBuilder()
            ->eagerCursor(true)
            ->field('feed.id')->notIn(array(null))
            ->sort('id', 'DESC');

        if (null !== $limit) {
            $q->limit($limit);
        }

        return $q->getQuery()->execute();
    }

    /**
     * Get the base query to fetch items
     *
     * @param  string   $id    Feed id
     * @param  int      $limit Number of items to return
     * @param  int      $skip  Item to skip before applying the limit
     *
     * @return Doctrine\ODM\MongoDB\Query\Query
     */
    private function getItemsByFeedIdQuery($id, $limit = null, $skip = null)
    {
        $q = $this->createQueryBuilder()
            ->field('feed.id')->equals($id)
            ->sort('id', 'DESC');

        if (null !== $limit) {
            $q->limit(0);
        }

        if (null !== $skip) {
            $q->skip(0);
        }

        return $q->getQuery();
    }

    /**
     * Find all logs for a given Feed id
     *
     * @param  int   $id Feed id
     *
     * @return Doctrine\ODM\MongoDB\LoggableCursor
     */
    public function findByFeedId($id)
    {
        return $this->getItemsByFeedIdQuery($id)
            ->execute();
    }

    /**
     * Retrieve the last log for a given Feed id
     *
     * @param  int   $id Feed id
     *
     * @return j0k3r\FeedBundle\Document\FeedLog
     */
    public function findLastItemByFeedId($id)
    {
        return $this->getItemsByFeedIdQuery($id, 1)
            ->getSingleResult();
    }
}
