services:
    # feed converter
    App\Converter\ConverterChain:
        class: App\Converter\ConverterChain

    feed.converter.instagram:
        class: App\Converter\Instagram
        arguments:
            - "@feed.extractor.instagram"
        calls:
            - [ setLogger, [ "@logger" ]]
        tags:
            -  { name: feed.converter, alias: instagram }
