services:
    # feed extractor
    App\Extractor\ExtractorChain:
        class: App\Extractor\ExtractorChain

    feed.extractor.imgur:
        class: App\Extractor\Imgur
        arguments:
            - "@imgur.client"
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: imgur }

    feed.extractor.twitter:
        class: App\Extractor\Twitter
        arguments:
            - "@twitter.client"
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: twitter }

    feed.extractor.tumblr:
        class: App\Extractor\Tumblr
        arguments:
            - "%env(TUMBLR_API_KEY)%"
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: tumblr }

    feed.extractor.vine:
        class: App\Extractor\Vine
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: vine }

    feed.extractor.instagram:
        class: App\Extractor\Instagram
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: instagram }

    feed.extractor.vidme:
        class: App\Extractor\Vidme
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: vidme }

    feed.extractor.gfycat:
        class: App\Extractor\Gfycat
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: gfycat }

    feed.extractor.flickr:
        class: App\Extractor\Flickr
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: flickr }

    feed.extractor.github:
        class: App\Extractor\Github
        arguments:
            - "%env(GITHUB_CLIENT_ID)%"
            - "%env(GITHUB_CLIENT_SECRET)%"
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: github }

    feed.extractor.deviantart:
        class: App\Extractor\Deviantart
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: deviantart }

    feed.extractor.camplus:
        class: App\Extractor\Camplus
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: camplus }

    feed.extractor.soundcloud:
        class: App\Extractor\Soundcloud
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: soundcloud }

    feed.extractor.vimeo:
        class: App\Extractor\Vimeo
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: vimeo }

    feed.extractor.youtube:
        class: App\Extractor\Youtube
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: youtube }

    feed.extractor.dailymotion:
        class: App\Extractor\Dailymotion
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: dailymotion }

    feed.extractor.spotify:
        class: App\Extractor\Spotify
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: spotify }

    feed.extractor.hackernews:
        class: App\Extractor\HackerNews
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: hackernews }

    feed.extractor.rue89:
        class: App\Extractor\Rue89
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: rue89 }

    feed.extractor.streamable:
        class: App\Extractor\Streamable
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: streamable }

    feed.extractor.ifttt:
        class: App\Extractor\Ifttt
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: ifttt }

    feed.extractor.redditimage:
        class: App\Extractor\RedditImage
        calls:
            - [ setLogger, [ "@logger" ]]
        tags:
            -  { name: feed.extractor, alias: redditimage }

    feed.extractor.redditvideo:
        class: App\Extractor\RedditVideo
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: redditvideo }

    feed.extractor.redditpost:
        class: App\Extractor\RedditPost
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: redditpost }

    feed.extractor.redditgallery:
        class: App\Extractor\RedditGallery
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: redditgallery }

    feed.extractor.giphy:
        class: App\Extractor\Giphy
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: giphy }

    feed.extractor.twitch:
        class: App\Extractor\Twitch
        arguments:
            - "%env(TWITCH_CLIENT_ID)%"
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: twitch }

    feed.extractor.periscope:
        class: App\Extractor\Periscope
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: periscope }
