# auth
login_check:
    path:  /login_check
    methods:  [POST]

logout:
    path:     /logout
    methods:  [GET]

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
