name: "CI"

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"

env:
  fail-fast: true

jobs:
  phpunit:
    name: "PHPUnit (PHP ${{ matrix.php }})"
    runs-on: "ubuntu-20.04"
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: f43_test
        ports:
          - 3306:3306
      rabbitmq:
        image: rabbitmq:3-alpine
        ports:
          - 5672:5672

    strategy:
      matrix:
        php:
          - "7.4"
          - "8.0"
          - "8.1"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php }}"
          tools: pecl, composer:v2
          extensions: pdo, pdo_mysql, curl, amqp
          ini-values: "date.timezone=Europe/Paris"
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"

      - name: "Install Node"
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: "Install dependencies with Yarn"
        run: "yarn install && yarn dev"

      - name: "Setup messenger queue"
        run: "php bin/console messenger:setup-transports --env=dev"

      - name: "Prepare database"
        run: "make prepare"

      - name: "Prepare logs"
        run: "mkdir -p build/logs"

      - name: "Run PHPUnit"
        run: "php bin/simple-phpunit -v"
